terence lin and shawn
jackietian/hotel-booking-system-tutorial pull request #15
Opened 2021-03-19 02:22 UTC by Shawn-Sydney

2021-03-19 22:48 UTC, jackietian requested changes

2021-03-19 22:48 UTC, jackietian commented on frontends/property/src/components/common/Carousel.js
> +		const deactive = document.getElementsByClassName("carousel-active");
this is jquery and native js ways of doing styles changes.

use react way pls. e.g conditional rendering.

2021-03-19 22:48 UTC, jackietian commented on frontends/property/src/components/Home.js
> +import Carousel from "./common/Carousel";
too many styles changes. I cannot focus on your changes. could you pls revert back the styles changes?

2021-03-19 22:48 UTC, jackietian commented on frontends/property/src/styles/carousel.scss
> +section.carousel {
section will be reused in main.scss. so better to move it back to `main.scss`

2021-03-20 06:39 UTC, terence1988 commented
PR updated?

2021-03-20 06:44 UTC, terence1988 commented on frontends/property/src/styles/carousel.scss
> +section.carousel {
done

2021-05-07 22:30 UTC, closed without merging